/**
 * 六爻模块公共导出（T110–T113 + W26 T280–T282）
 */

export {
  LIUYAO_DATA_SOURCES,
  TRIGRAMS,
  TRIGRAM_BY_NAME,
  TRIGRAM_BY_BINARY,
  getTrigram,
  getTrigramByBinary,
  type TrigramEntry,
  HEXAGRAMS,
  HEXAGRAM_BY_INDEX,
  HEXAGRAM_BY_UPPER_LOWER,
  HEXAGRAM_BY_BINARY,
  getHexagram,
  getHexagramByTrigrams,
  getHexagramByBinary,
} from "./data";

export {
  castLiuyao,
  buildChart,
  LIUYAO_ENGINE_VERSION,
  castingSchoolOf,
  methodNoteOf,
  SCHOOL_LABEL,
  METHOD_NOTE,
  type CastLiuyaoInput,
} from "./cast";

export {
  analyzeLiuyao,
  enrichChart,
  listDongYao,
  ensureBenBian,
  resolveYongShen,
  resolveYongShenDetail,
  resolveYongShenStatus,
  assignLiuqin,
  shiYingFromBinary,
  analyzeDongBian,
  dongBianSectionBody,
  xunKongOfDay,
  xunShouOfDay,
  isBranchKong,
  resolveCastTimeContext,
  resolveYingQi,
  assignLiushen,
  resolveFushen,
  branchYuePo,
  branchRiChong,
  isBranchChong,
  inferQuestionCategory,
  type LiuyaoAnalysis,
  type YongShenResolved,
  type YongShenStatus,
  type YaoLiuqin,
  type Liuqin,
  type DongBianItem,
  type WuxingRelation,
  type HuitouKind,
  type YongShenGender,
  type CastTimeContext,
  type YingQiResult,
  type FushenItem,
} from "./analyze";

export type {
  LiuyaoMethod,
  LiuyaoCastingSchool,
  LiuyaoRandomSource,
  LiuyaoQuestionCategory,
  LiuyaoChartMeta,
  YaoValue,
  YaoPosition,
  LiuyaoLine,
  GuaRef,
  LiuyaoChart,
  TrigramName,
  HexagramEntry,
  LiuqinName,
  LiushenName,
} from "@/lib/types/liuyao";
