/** Generated by scripts/sync-bazi-skill.mjs. Do not edit by hand. */
export const BAZI_SKILL_PROVENANCE = {
  "skillRef": "bazi-skill",
  "source": "project-synced-skill",
  "sourceLicense": "MIT",
  "referenceManifestVersion": "1",
  "referenceHash": "07552d25facd22555b00f60b75073e587959dcad2808667d00e342df081470eb",
  "files": [
    {
      "path": "LICENSE",
      "sha256": "44040fe9b9918cd13978d272955960fbb30474a2d08eb210e0bd10a86ade1dfe"
    },
    {
      "path": "README.md",
      "sha256": "c537ead9b7c3f31bc5a84f9ffa27b2d417cc718e3c0c75c3fc15136ae2e6e4a4"
    },
    {
      "path": "SKILL.md",
      "sha256": "bd2e76d0778cae88666a335e339955e7cf179ef2a740353bb2556f8b0ddb9a68"
    },
    {
      "path": "references/wuxing-tables.md",
      "sha256": "25648384e04666e7dd0a04efa9b7c124c3b457fa5071535d733313fe3e06dc9b"
    },
    {
      "path": "references/shichen-table.md",
      "sha256": "f025ba17d2bdb38f0e282fe71329df51a37b96ee4eff14196c65def6f41dfbc6"
    },
    {
      "path": "references/dayun-rules.md",
      "sha256": "0b2f4db41644beb425eaeec861e9b3e40b33aa4df52d9ccf971a0141fb49e69b"
    },
    {
      "path": "references/classical-texts.md",
      "sha256": "c6537104c245039607ecfabdcace787ddcb6ec20e7422933212498e38dea0a7a"
    }
  ],
  "execution": "deterministic-project-engine"
} as const;
