/** Generated by scripts/sync-bazi-skill.mjs. Do not edit by hand. */
export const BAZI_SKILL_PROVENANCE = {
  "skillRef": "bazi-skill",
  "source": "project-synced-skill",
  "sourceLicense": "MIT",
  "referenceManifestVersion": "1",
  "referenceHash": "3c48faf83055dff34e9f3d86777b387df40e30ffd804f7e3d987a8d82a84b72e",
  "files": [
    {
      "path": "LICENSE",
      "sha256": "28ce6f2a50b8e8aba67c0b3837152d7aa9389cd677ed34acc624a7aff81dacf4"
    },
    {
      "path": "README.md",
      "sha256": "33a9f0d73a518b313f9c171ff61e5148510506b8b27c6117ad5e2f0ee45d6eb2"
    },
    {
      "path": "SKILL.md",
      "sha256": "ee9f48acda7cd237b4d04789ea2815cf37a14849cd300b4ad529739928017386"
    },
    {
      "path": "references/wuxing-tables.md",
      "sha256": "167982bb7fd5ddc0f3dcfafe6ec377c92fa2d4bd90153b72c89d65888a7d419f"
    },
    {
      "path": "references/shichen-table.md",
      "sha256": "bcddb4c87d179d52ea15740c75edcfa2f99f89aef23bc5068fc88c87b4068768"
    },
    {
      "path": "references/dayun-rules.md",
      "sha256": "70e35df806e7d6ede9e3ab6524bd2088d3ce9ac8a8e8d6177c84abe0e2b03562"
    },
    {
      "path": "references/classical-texts.md",
      "sha256": "43094d2069567a37757fd6c6d8927c3936d446ba2f28378dd1a1387a9768026b"
    }
  ],
  "execution": "deterministic-project-engine"
} as const;
